Update cfn-lint.yml

diff --git a/.github/workflows/cfn-lint.yml b/.github/workflows/cfn-lint.yml
--- a/.github/workflows/cfn-lint.yml
+++ b/.github/workflows/cfn-lint.yml
@@ -43,3 +43,42 @@ jobs:
         with:
           input_path: .
           extra_args: --fail-on-warnings
+
+  python-security-scan:
+    name: Python Security Scan
+    runs-on: ubuntu-latest
+ 
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install bandit
+      - name: Run Bandit scan and capture output
+        id: bandit
+        run: |
+          echo "--------------------Starting python code scanning------------------------------"
+          # bandit -c bandit.yaml -r . -f txt -o bandit-results.txt
+          bandit -r . -f txt -o bandit-results.txt
+          EXIT_CODE=$?
+          echo "=========================="
+          if [ $EXIT_CODE -eq 1 ]; then
+            echo "Security issues found!"
+            exit 1
+          elif [ $EXIT_CODE -eq 0 ]; then
+            echo "No security issues found"
+          else
+            echo "Scan failed to complete"
+            exit 1
+          fi
+ 
+      - name: Bandit Scan results
+        if: always()
+        run: |
+          echo "---------------Bandit Scan Report--------------------"
+          if [ -f bandit-results.txt ]; then
+            cat bandit-results.txt
+          else  
+            echo "No files found "
+          fi
